config/routes.rb
Rails.application.routes.draw do
  resources :monsters
  resources :dms
  resources :actions, only: [:create, :update, :destroy]
  get '/login' => 'sessions#new'
  post '/login' => 'sessions#create'
  post '/logout' => 'sessions#destroy'
  post '/add/:id' => 'monsters#add'
  post '/remove/:id' => 'monsters#remove'
  post '/monsters/order' => 'monsters#order'
  root 'sessions#new'
end

app/models/ability.rb
class Ability < ApplicationRecord
    belongs_to :monster
end

app/models/action.rb
class Action < ApplicationRecord
    belongs_to :monster 
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/dm.rb
class Dm < ApplicationRecord
    has_secure_password
    has_many :dm_monsters
    has_many :monsters, through: :dm_monsters
    validates :name, presence: true, uniqueness: {case_sensitive: false}
    validates :email, presence: true
end

app/models/dm_monster.rb
class DmMonster < ApplicationRecord
    belongs_to :dm 
    belongs_to :monster 
end

app/models/monster.rb
class Monster < ApplicationRecord
    has_many :dm_monsters
    has_many :dms, through: :dm_monsters
    has_many :actions
    accepts_nested_attributes_for :actions
    has_many :abilities
    accepts_nested_attributes_for :abilities
    validates :name, presence: true
    validates :ac, presence: true
    validates :hp, presence: true
    validates :speed, presence: true
    validates :strength, presence: true
    validates :dexterity, presence: true
    validates :constitution, presence: true
    validates :intelligence, presence: true
    validates :wisdom, presence: true
    validates :charisma, presence: true
    validates :cr, presence: true
end

app/controllers/actions_controller.rb
class ActionsController < ApplicationController

    before_action :find_action, except: [:create]

    def create
        action = Action.create(name: params[:name], description: params[:description], monster_id: params[:monster_id])
        home_monster
    end 

    def update
        @action.update(name: params[:name], description: params[:description])
        home_monster
    end 

    def destroy
        @action.destroy 
        home_monster
    end 

    private

    def find_action
        @action = Action.find(params[:id])
    end 

    def home_monster
        redirect_to monster_path(Monster.last)
    end 

end 

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  before_action :current_dm

  def current_dm
    @dm = (Dm.find_by(id: session[:dm_id]) || Dm.new)
  end

  def logged_in?
    current_dm.id != nil
  end

  def require_logged_in
    return redirect_to(controller: 'sessions', action: 'new') unless logged_in?
  end
end

app/controllers/dms_controller.rb
class DmsController < ApplicationController
    
    before_action :require_logged_in, except: [:new, :create]

    def index 
        @dms = Dm.all 
    end 

    def show 
        if my_profile?
            @mine = true 
        end 
        @profile_dm = Dm.find(params[:id])
    end 

    def new 
        @dm = Dm.new 
    end 

    def create 
        @dm = Dm.new(dm_params)
        if @dm.valid? 
            @dm.save
            session[:dm_id] = @dm.id
            redirect_to dm_path(@dm)
        else 
            render :new
        end 
    end 

    def edit 
        unless my_profile?
            redirect_to dm_path(@dm)
        end 
    end 

    def update 
        @dm.update(dm_params)
        redirect_to dm_path(@dm)
    end 

    def destroy 
        @dm.monsters.each do |m|
            decreased_popularity = m.popularity - 1
            m.update(popularity: decreased_popularity)
        end 
        @dm.destroy 
        redirect_to dms_path 
    end 

    private 

    def dm_params 
        params.require(:dm).permit(:name, :password, :password_confirmation, :email)
    end 

    def my_profile?
        params[:id].to_i == @dm.id
    end 

end

app/controllers/monsters_controller.rb
class MonstersController < ApplicationController

    before_action :require_logged_in
    before_action :find_monster, only: [:show, :edit, :update, :destroy, :add, :remove]
    @@monsters = nil

    def index 
        @monsters = Monster.all
        if @@monsters 
            @monsters = @@monsters
        end 
    end 

    def order 
        @monsters = Monster.all
        category = params[:category]
        min = params[:minimum].to_i
        max = params[:maximum].to_i
        unless category == "Any"
            @monsters = @monsters.select do |m|
                m.category == category
            end 
        end 
        if min || max 
            if max == 0
                max = 100
            end 
            @monsters = @monsters.select do |m|
                m.cr >= min && m.cr <= max
            end 
        end 
        if params[:order] == "Alphabetically"
            @@monsters = @monsters.sort_by {|m| m.name} 
        else 
            @@monsters = @monsters.sort_by {|m| m.popularity}.reverse
        end 
        redirect_to monsters_path 
    end 

    def show 
        @creator = Dm.find(@monster.creator_id)
    end 

    def new 
        @monster = Monster.new 
        @action = Action.new 
        @default = 10 
    end 

    def create 
        @monster = Monster.new(monster_params)
        if @monster.valid? 
            @monster.save 
            @monster.update(creator_id: @dm.id, popularity: 0)
            DmMonster.create(dm_id: @dm.id, monster_id: @monster.id)
            @action = Action.new(name: params[:monster][:action][:name], description: params[:monster][:action][:description], monster_id: @monster.id)
            if @action.name || @action.description 
                unless @action.name
                    @action.name = "Please add a name"
                end 
                unless @action.description 
                    @action.description = "Please add a description"
                end 
                @action.save 
            end 
            redirect_to monster_path(@monster)
        else 
            render :new 
        end 
    end 

    def edit 
        if session[:dm_id] != @monster.creator_id
            redirect_to dm_path(@dm)
        end 
    end 

    def update 
        @updated_monster = Monster.new(monster_params)
        if @updated_monster.valid?
            @monster.update(monster_params)
            redirect_to monster_path(@monster)
        else 
            render :edit 
        end 
    end 

    def destroy 
        @monster.destroy 
        redirect_to monsters_path 
    end 

    def add 
        DmMonster.find_or_create_by(dm_id: session[:dm_id], monster_id: params[:id])
        increased_popularity = @monster.popularity + 1 
        @monster.update(popularity: increased_popularity)
        redirect_to dm_path(@dm)
    end 

    def remove 
        DmMonster.find_by(dm_id: session[:dm_id], monster_id: params[:id]).destroy
        decreased_popularity = @monster.popularity - 1
        @monster.update(popularity: decreased_popularity)
        redirect_to dm_path(@dm)
    end 

    private 

    def find_monster
        @monster = Monster.find(params[:id])
    end 

    def monster_params 
        params.require(:monster).permit(:name, :size, :category, :alignment, :ac, :hp, :speed, :strength, :dexterity, :constitution, :intelligence, :wisdom, :charisma, :cr, :image)
    end 

end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end
  
    def create
      dm = Dm.find_by(name: params[:dm][:name])
      dm = dm.try(:authenticate, params[:dm][:password])
      if dm 
        session[:dm_id] = dm.id
        @dm = dm
        redirect_to dm_path(@dm)
      else 
        flash[:error] = "Incorrect login"
        redirect_to controller: 'sessions', action: 'new'
      end 
    end
  
    def destroy
      session.clear 
      redirect_to '/'
    end
  end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/dm_monsters_helper.rb
module DmMonstersHelper
end

app/helpers/dms_helper.rb
module DmsHelper
end

app/helpers/monsters_helper.rb
module MonstersHelper
end

app/views/dms/edit.html.erb
<div class="dm_pages">
<h1> Edit your profile </h1>

<%= form_for @dm do |f| %>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <%= f.submit "Change email" %>
<% end %>

<%= button_to "Delete Dungeon Master", dm_path(@dm), method: :delete %>

<%= button_to "Return to your proflie", dm_path(@dm), method: :get %>
</div>

app/views/dms/index.html.erb
<div class="dm_pages">
<h1> Dungeon Masters </h1>
<h2> Welcome <%= session[:name] %> </h2>

<ul>
    <% @dms.each do |d| %>
    <li><%= link_to d.name, dm_path(d) %></li>
    <% end %>
</ul>

<%= button_to "Return to your proflie", dm_path(@dm), method: :get %>

<%= button_to "Go to monster index", monsters_path, method: :get %> 
</div>

app/views/dms/new.html.erb
<div class="dm_pages">
<h1> Create a new Dungeon Master </h1>

<%= render partial: "shared/error_list", locals: {new_object: @dm}  %>

<%= form_for @dm, controller: 'dms', action: 'create' do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :password %>
    <%= f.password_field :password %>
    <br>
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.label :email %>
    <%= f.text_field :email %>
    <br>
    <%= f.submit "create" %>
  <% end %>
</div>

app/views/dms/show.html.erb
<div class="dm_pages">

<h1> DM Profile for <%= @profile_dm.name %></h1>

<h3>Email: <%= @profile_dm.email %></h3>

<h3>Created monsters: </h3>

<ul>
<% @profile_dm.monsters.each do |m| %>
    <% if @profile_dm.id == m.creator_id %>
        <li><%= link_to m.name, monster_path(m) %></li>
    <% end %>
<% end %>
</ul>

<h3>Added monsters: </h3>

<ul>
<% @profile_dm.monsters.each do |m| %>
    <% if @profile_dm.id != m.creator_id %>
        <li><%= link_to m.name, monster_path(m) %></li>
    <% end %>
<% end %>
</ul>

<% if @mine == true %>
    <%= button_to "Edit your profile", edit_dm_path(@dm), method: :get %>
<% end %>

<% if @mine == true %>
    <%= button_to "Create new monster", new_monster_path, method: :get %>
<% end %>

<%= button_to "Go to monster index", monsters_path, method: :get %>

<%= button_to "Go to DM index", dms_path, method: :get %>

<% if @mine == true %>
    <%= button_to "Logout", '/logout', method: :post %>
<% else %>
    <%= button_to "Return to your proflie", dm_path(@dm), method: :get %>
<% end %>
<div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>WillHarrisMod2Project</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.css">
    <script src="https://cdn.jsdelivr.net/npm/semantic-ui@2.4.2/dist/semantic.min.js"></script>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/monsters/edit.html.erb
<div class="monster_display_pages">
<h1> Edit <%= @monster.name %> </h1>

<br>
<img src="<%= @monster.image %>" class="monster_image">
<br>

<% if @updated_monster %>
<%= render partial: "shared/error_list", locals: {new_object: @updated_monster}  %>
<% end %>

<%= form_for @monster do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :size %>
    <%= f.select :size, ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"] %>
    <br>
    <%= f.label :category %>
    <%= f.select :category, ["Aberration", "Beast", "Celestial", "Construct", "Dragon", "Elemental", "Fey", "Fiend", "Giant", "Humanoid", "Monstrosity", "Ooze", "Plant", "Undead"] %>
    <br>
    <%= f.label :alignment %>
    <%= f.select :alignment, ["Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "True Neutral", "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil"] %>
    <br>
    <%= f.label :ac %>
    <%= f.number_field :ac %>
    <br>
    <%= f.label :hp %>
    <%= f.number_field :hp %>
    <br>
    <%= f.label :speed %>
    <%= f.number_field :speed %>
    <br>
    <%= f.label :strength %>
    <%= f.number_field :strength %>
    <br>
    <%= f.label :dexterity %>
    <%= f.number_field :dexterity %>
    <br>
    <%= f.label :constitution %>
    <%= f.number_field :constitution %>
    <br>
    <%= f.label :intelligence %>
    <%= f.number_field :intelligence %>
    <br>
    <%= f.label :wisdom %>
    <%= f.number_field :wisdom %>
    <br>
    <%= f.label :charisma %>
    <%= f.number_field :charisma %>
    <br>
    <%= f.label :cr %>
    <%= f.number_field :cr %>
    <br>
    <%= f.label :image %>
    <%= f.text_field :image %>
    <br>
    <%= f.submit "Update monster stats" %>
<% end %>

<br> 

<h3>Edit actions </h3>

<% @monster.actions.each do |act| %>
    <%= form_tag(action_path(act), method: :patch) do %>
        <%= label_tag :name %>
        <%= text_field_tag :name, value = "#{act.name}" %>
        <%= label_tag :description %>
        <%= text_area_tag :description, value = "#{act.description}" %>
        <%= submit_tag "Edit action" %>
    <% end %>
    <%= button_to "Delete this action", action_path(act), method: :delete %>
    <br>

<% end %>


<h3>Add an action </h3>

<%= form_tag actions_path do %>
    <%= label_tag :name %>
    <%= text_field_tag :name %>
    <%= label_tag :description %>
    <%= text_area_tag :description %>
    <%= hidden_field_tag 'monster_id', "#{@monster.id}" %>
    <%= submit_tag "Add action" %>
<% end %>

<%= button_to "Delete monster", monster_path(@monster), method: :delete %>
<%= button_to "Return to monster index", dms_path, method: :get %>
<%= button_to "Return to your proflie", dm_path(@dm), method: :get %>
</div>

app/views/monsters/index.html.erb
<div class="monster_navigation_pages">
<h1> Monsters </h1>

<%= form_tag url_for('/monsters/order'), method: 'post' do %>
    <%= label_tag "Order" %>
    <%= select_tag "order", raw("<option>Alphabetically</option><option>Popularity</option>") %>
    <%= label_tag "Category" %>
    <%= select_tag "category", raw("<option>Any</option><option>Aberration</option><option>Beast</option><option>Celestial</option><option>Construct</option><option>Dragon</option><option>Elemental</option><option>Fey</option><option>Fiend</option><option>Giant</option><option>Humanoid</option><option>Monstrosity</option><option>Ooze</option><option>Plant</option><option>Undead</option>") %>                                                                                                                                                                                                                                                            
    <%= label_tag "CR minimum:" %>
    <%= number_field_tag "minimum" %>
    <%= label_tag "CR maximum:" %>
    <%= number_field_tag "maximum" %>
    <%= submit_tag "Apply" %>
<% end %> 

<ul>
    <% @monsters.each do |m| %>
    <li><%= link_to m.name, monster_path(m) %> users: <%= m.popularity %></li>
    <% end %>
</ul>

<%= button_to "Return to your proflie", dm_path(@dm), method: :get %>
</div>

app/views/monsters/new.html.erb
<div class="monster_navigation_pages">
<h1> Create a new monster</h1>

<%= render partial: "shared/error_list", locals: {new_object: @monster}  %>

<%= form_for @monster do |f| %>
    <%= f.label :name %>
    <%= f.text_field :name %>
    <br>
    <%= f.label :size %>
    <%= f.select :size, ["Tiny", "Small", "Medium", "Large", "Huge", "Gargantuan"] %>  
    <br>
    <%= f.label :category %>
    <%= f.select :category, ["Aberration", "Beast", "Celestial", "Construct", "Dragon", "Elemental", "Fey", "Fiend", "Giant", "Humanoid", "Monstrosity", "Ooze", "Plant", "Undead"] %>  
    <br>
    <%= f.label :alignment %>
    <%= f.select :alignment, ["Lawful Good", "Neutral Good", "Chaotic Good", "Lawful Neutral", "True Neutral", "Chaotic Neutral", "Lawful Evil", "Neutral Evil", "Chaotic Evil"] %>  
    <br>
    <%= f.label :ac %>
    <%= f.number_field :ac, value: 10 %>
    <br>
    <%= f.label :hp %>
    <%= f.number_field :hp, value: 15 %>
    <br>
    <%= f.label :speed %>
    <%= f.number_field :speed, value: 30 %>
    <br>
    <%= f.label :strength %>
    <%= f.number_field :strength, value: @default %>
    <br>
    <%= f.label :dexterity %>
    <%= f.number_field :dexterity, value: @default %>
    <br>
    <%= f.label :constitution %>
    <%= f.number_field :constitution, value: @default %>
    <br>
    <%= f.label :intelligence %>
    <%= f.number_field :intelligence, value: @default %>
    <br>
    <%= f.label :wisdom %>
    <%= f.number_field :wisdom, value: @default %>
    <br>
    <%= f.label :charisma %>
    <%= f.number_field :charisma, value: @default %>
    <br>
    <%= f.label :cr %>
    <%= f.number_field :cr, value: 1 %>
    <br>
    <%= f.label :image %>
    <%= f.text_field :image %>
    <br>
    <h3> Add an action </h3>
    <%= f.fields_for :action do |nf| %>
        <%= nf.label :name %>
        <%= nf.text_field :name %>
        <br>
        <%= nf.label :description %>
        <%= nf.text_area :description %>
    <% end %>
    <br>
    <%= f.submit "Create monster" %>
<% end %>
</div>

app/views/monsters/show.html.erb
<div class="monster_display_pages">
<h1> Monster Profile: <%= @monster.name %> </h1>
<h3>Created by: <%= link_to @creator.name, dm_path(@creator) %> </h3>

<br>
<img src="<%= @monster.image %>" class="monster_image">
<br>

<p>Size: <%= @monster.size %></p>
<p>Category: <%= @monster.category %></p>
<p>Alignment: <%= @monster.alignment %></p>
<p>AC: <%= @monster.ac %></p>
<p>HP: <%= @monster.hp %></p>
<p>Speed: <%= @monster.speed %></p>
<p>Strength: <%= @monster.strength %></p>
<p>Dexterity: <%= @monster.dexterity %></p>
<p>Constitution: <%= @monster.constitution %></p>
<p>Intelligence: <%= @monster.intelligence %></p>
<p>Wisdom: <%= @monster.wisdom %></p>
<p>Charisma: <%= @monster.charisma %></p>
<p>CR: <%= @monster.cr %></p>
<p>Popularity: <%= @monster.popularity %> <%= if @monster.popularity == 1; "user"; else; "users"; end %></p>

<br>

<p> Actions: </p>
<% @monster.actions.each do |a| %>
    Name: <%= a.name %>
    <br>
    Description: <%= a.description %>
    <br>
    <br>
<% end %>

<br>

<% if session[:dm_id] == @monster.creator_id %>
    <%= button_to "Edit this monster", edit_monster_path(@monster), method: :get %>
<% end %>

<% if @creator.id != @dm.id %>
    <% if DmMonster.find_by(dm_id: @dm.id, monster_id: @monster.id)%>
        <%= button_to "Remove this monster from your list", "/remove/#{@monster.id}", method: :post %>
    <% else %>
        <%= button_to "Add this monster to your list", "/add/#{@monster.id}", method: :post %>
    <% end %>
<% end %>

<%= button_to "Return to monster index", monsters_path, method: :get %>

<%= button_to "Return to your proflie", dm_path(@dm), method: :get %>
</div>

app/views/shared/_error_list.html.erb
<% if new_object.errors %>
    <ul class="error_list">
        <% new_object.errors.full_messages.each do |message| %>
            <li><%= message %></li>
        <% end %>
    </ul>
<% end %>

app/views/shared/_menu_bar.html.erb
<div class="ui three item menu">
  <a class="active item">Editorials</a>
  <a class="item">Reviews</a>
  <a class="item">Upcoming Events</a>
</div>